### ISSUE TITLE
Interpretation of the output

### ISSUE THREAD

**Issue by Rohit-Satyam** [TulsaBioinformaticsToolsmith/Look4TRs#2]
Hi Alfredo!!

I am interested in using your tool on a contig-level genome assembly. I gave it a test run and I wish to understand what does last two columns of the output file represents. Also, strand information isn't available does it perform prediction for positive-strand only??

```bash
while read p; 
do 
name=$(echo $p | xargs -n 1 basename | cut -f 1 -d.); 
cp $p . ; 
../bin/Look4TRs --adr . --out res --default 1> logs/${name}.out 2> logs/${name}.err; 
ls *.txt | xargs -I {} mv {} ${name}_{};  ## To rename the HMM, GLM and CHMP files
mv *.txt models/;  ## and move them in models directory
rm *.fa; 
done < files
```
I am using the above loop to execute it on multiple fasta files(contig/scaffold level )!!

**Comment by hani-girgis** [comment]
Hi, Rohit.

Thanks for your interest in Look4TRs.

The column before the last is the repeated motif. The last column is the identity score between a sequence consisting of exact copies of the repeated motif and the real sequence found in the genome. A score of 1 indicates that all copies of the repeated motif in the real sequence are exact. Yes, Look4TRs performs prediction on the positive strand only.

Let me know if you have additional questions.

Best regards.
