### ISSUE TITLE
Error: Incorrect number of arguments (7) for the "--thr" flag!

### ISSUE THREAD

**Issue by shelkmike** [TulsaBioinformaticsToolsmith/Look4TRs#3]
I run Look4TRs with the following command:
`/gpfs/mshelkunov/Work/Tools/Look4TRs/bin/Look4TRs --adr Input_folder --out Results --thr 22 --default`

Look4TRs terminates with the following error:
`Error: Incorrect number of arguments (7) for the "--thr" flag!`

**Comment by hani-girgis** [comment]
Hi. Thanks for your interest in our tool—Loot4TRs. 

NOTE: After supplying the required options, either provide a single default option, or provide all of the parameter options. So you cannot use --thr with --default.
